BestRestaurants/Models/BestRestaurantsContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Models
{
  public class BestRestaurantsContext : DbContext
  {
    public virtual DbSet<Restaurant> Restaurants { get; set; }
    public virtual DbSet<Cuisine> Cuisines { get; set; }

    public BestRestaurantsContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

BestRestaurants/Models/Cuisine.cs
using System;
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Cuisine
  {
    public int CuisineId { get; set; }
    public string Type { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; }

    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>();
    }
  }
}

BestRestaurants/Models/Restaurant.cs
using System;
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Restaurant
  {
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public string SundayOpen { get; set; } 
    public string SundayClose { get; set; }
    public string MondayOpen { get; set; }
    public string MondayClose { get; set; }
    public string TuesdayOpen { get; set; }
    public string TuesdayClose { get; set; }
    public string WednesdayOpen { get; set; }
    public string WednesdayClose { get; set; }
    public string ThursdayOpen { get; set; }
    public string ThursdayClose { get; set; }
    public string FridayOpen { get; set; }
    public string FridayClose { get; set; }
    public string SaturdayOpen { get; set; }
    public string SaturdayClose { get; set; }
    public int CuisineId { get; set; }
    public virtual Cuisine Cuisine { get; set; }
  }
}

BestRestaurants/Controllers/CuisinesController.cs
using BestRestaurants.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public CuisinesController(BestRestaurantsContext db)
    {
      _db = db;
    }

    [HttpGet("/Cuisines")]
    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.Include(cuisine => cuisine.Restaurants).ToList();
      return View(model);
    }

    [HttpGet("/Cuisines/new")]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost("/Cuisines/new")]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpGet("/Cuisines/{id}")]
    public ActionResult Show(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpGet("/Cuisines/{id}/edit")]
    public ActionResult Edit(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost("/Cuisines/{id}/edit")]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpGet("/Cuisines/{id}/delete")]
    public ActionResult Delete(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost("/Cuisines/{id}/delete"), ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurants.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

BestRestaurants/Controllers/RestaurantsController.cs
using BestRestaurants.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public RestaurantsController(BestRestaurantsContext db)
    {
      _db = db;
    }

    [HttpGet("/Restaurants")]
    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurant => restaurant.Cuisine).ToList();
      return View(model);
    }

    [HttpGet("/Restaurants/new")]
    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Type");
      return View();
    }

    [HttpPost("/Restaurants/new")]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpGet("/Restaurants/{id}")]
    public ActionResult Show(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpGet("/Restaurants/{id}/edit")]
    public ActionResult Edit(int id)
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Type");
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost("/Restaurants/{id}/edit")]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpGet("/Restaurants/{id}/delete")]
    public ActionResult Delete(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost("/Restaurants/{id}/delete"), ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine;

<h4>Add a new Cuisine</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Type)
  @Html.TextBoxFor(model => model.Type, new { required="required" })
  <br>
  <input type="submit" value="Add New Cuisine" />
}
<br>
<p>@Html.ActionLink("Show All Cuisines", "Index")</p>

BestRestaurants/Views/Cuisines/Delete.cshtml
@{
  Layout="_Layout";
}

@using BestRestaurants.Models
@model BestRestaurants.Models.Cuisine

@if (Model.Restaurants.Count == 0)
{
  <h2>Are you sure you want to delete this?</h2>
  <h3>Type: @Html.DisplayFor(model => model.Type)</h3>
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" />
  }
}
else
{
  <h2>Before you can delete this you must first empty the list of restaurants.</h2>
  <h3>This can be done by either deleting the restaurant or changing which cuisine it is in.</h3>
  <ul>
  @foreach (Restaurant restaurant in Model.Restaurants)
  {
    <li>@Html.ActionLink($"{restaurant.Name}", "Show", "Restaurants", new { id = restaurant.RestaurantId })</li>
  }
  </ul>
}

@Html.ActionLink("Back to List", "Index")

BestRestaurants/Views/Cuisines/Edit.cshtml
@{
  Layout="_Layout";
}

@model BestRestaurants.Models.Cuisine

<h2>Edit</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)

  @Html.LabelFor(model => model.Type)
  @Html.EditorFor(model => model.Type)

  <input type="submit" value="Save" />
}
<br>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models

<h1>Cuisines:</h1>

@if(@Model.Count == 0)
{
  <h3>No Cuisines are in this database</h3>
}

@foreach (Cuisine cuisine in Model)
{
    <li>@Html.ActionLink($"{cuisine.Type}", "Show", new { id = cuisine.CuisineId })</li>
}
<br>
<p>@Html.ActionLink("Add new Cuisine", "Create")</p>
<br>
<p>@Html.ActionLink("See By Restaurants", "Index", "Restaurants")</p>

BestRestaurants/Views/Cuisines/Show.cshtml
@{
  Layout="_Layout";
}

@using BestRestaurants.Models
@model BestRestaurants.Models.Cuisine

<h2>Cuisine Details:</h2>
<br>
<h3>Type: @Html.DisplayFor(model => model.Type)</h3>
<br>
<h3>Restaurants:</h3>
<ul>
  @foreach (Restaurant restaurant in Model.Restaurants)
  {
    <li>@Html.ActionLink($"{restaurant.Name}", "Show", "Restaurants", new { id = restaurant.RestaurantId })</li>
  }
</ul>
<br>
<p>@Html.ActionLink("Edit Details", "Edit", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Delete Entry", "Delete", new { id = Model.CuisineId})</p>
<br>
<p>@Html.ActionLink("Show All Cuisines", "Index")</p>

BestRestaurants/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<p>@Html.ActionLink("See By Restaurants", "Index", "Restaurants")</p>
<p>@Html.ActionLink("See By Cuisines", "Index", "Cuisines")</p>

BestRestaurants/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant;

<h4>Add a new Restaurant</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name, new { required="required"})
  <br>
  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")
  <br>
  <p>Times of operation:</p>
  <p>Sunday:</p>
  @Html.LabelFor(model => model.SundayOpen)
  @Html.EditorFor(model => model.SundayOpen, new { required="required" })
  @Html.LabelFor(model => model.SundayClose)
  @Html.EditorFor(model => model.SundayClose, new { required="required" })
  <br>
  <p>Monday:</p>
  @Html.LabelFor(model => model.MondayOpen)
  @Html.EditorFor(model => model.MondayOpen, new { required="required" })
  @Html.LabelFor(model => model.MondayClose)
  @Html.EditorFor(model => model.MondayClose, new { required="required" })
  <br>
  <p>Tuesday:</p>
  @Html.LabelFor(model => model.TuesdayOpen)
  @Html.EditorFor(model => model.TuesdayOpen, new { required="required" })
  @Html.LabelFor(model => model.TuesdayClose)
  @Html.EditorFor(model => model.TuesdayClose, new { required="required" })
  <br>
  <p>Wednesday:</p>
  @Html.LabelFor(model => model.WednesdayOpen)
  @Html.EditorFor(model => model.WednesdayOpen, new { required="required" })
  @Html.LabelFor(model => model.WednesdayClose)
  @Html.EditorFor(model => model.WednesdayClose, new {  required="required" })
  <br>
  <p>Thursday:</p>
  @Html.LabelFor(model => model.ThursdayOpen)
  @Html.EditorFor(model => model.ThursdayOpen, new { required="required" })
  @Html.LabelFor(model => model.ThursdayClose)
  @Html.EditorFor(model => model.ThursdayClose, new { required="required" })
  <br>
  <p>Friday:</p>
  @Html.LabelFor(model => model.FridayOpen)
  @Html.EditorFor(model => model.FridayOpen, new { required="required" })
  @Html.LabelFor(model => model.FridayClose)
  @Html.EditorFor(model => model.FridayClose, new { required="required" })
  <br>
  <p>Saturday:</p>
  @Html.LabelFor(model => model.SaturdayOpen)
  @Html.EditorFor(model => model.SaturdayOpen, new { required="required" })
  @Html.LabelFor(model => model.SaturdayClose)
  @Html.EditorFor(model => model.SaturdayClose, new { required="required" })
  <br>
  <input type="submit" value="Add new Restaurant" />
}


<p>@Html.ActionLink("Show All Restaurants", "Index")</p>

BestRestaurants/Views/Restaurants/Delete.cshtml
@{
  Layout="_Layout";
}

@using BestRestaurants.Models
@model BestRestaurants.Models.Restaurant

<h2>Are you sure you want to delete this?</h2>

<h3>Name: @Html.DisplayFor(model => model.Name)</h3>
<h3>Type of cuisine: @Model.Cuisine.Type</h3>
<h3>Times:</h3>
<h4>Sunday:</h4>
<p>From @Html.DisplayFor(model => model.SundayOpen) to @Html.DisplayFor(model => model.SundayClose)</p>
<h4>Monday:</h4>
<p>From @Html.DisplayFor(model => model.MondayOpen) to @Html.DisplayFor(model => model.MondayClose)</p>
<h4>Tuesday:</h4>
<p>From @Html.DisplayFor(model => model.TuesdayOpen) to @Html.DisplayFor(model => model.TuesdayClose)</p>
<h4>Wednesday:</h4>
<p>From @Html.DisplayFor(model => model.WednesdayOpen) to @Html.DisplayFor(model => model.WednesdayClose)</p>
<h4>Thursday:</h4>
<p>From @Html.DisplayFor(model => model.ThursdayOpen) to @Html.DisplayFor(model => model.ThursdayClose)</p>
<h4>Friday:</h4>
<p>From @Html.DisplayFor(model => model.FridayOpen) to @Html.DisplayFor(model => model.FridayClose)</p>
<h4>Saturday:</h4>
<p>From @Html.DisplayFor(model => model.SaturdayOpen) to @Html.DisplayFor(model => model.SaturdayClose)</p>
<br>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

BestRestaurants/Views/Restaurants/Edit.cshtml
@{
  Layout="_Layout";
}

@model BestRestaurants.Models.Restaurant

<h2>Edit</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name, new { required="required"})
  <br>
  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")
  <br>
  <p>Times of operation:</p>
  <p>Sunday:</p>
  @Html.LabelFor(model => model.SundayOpen)
  @Html.EditorFor(model => model.SundayOpen, new { required="required" })
  @Html.LabelFor(model => model.SundayClose)
  @Html.EditorFor(model => model.SundayClose, new { required="required" })
  <br>
  <p>Monday:</p>
  @Html.LabelFor(model => model.MondayOpen)
  @Html.EditorFor(model => model.MondayOpen, new { required="required" })
  @Html.LabelFor(model => model.MondayClose)
  @Html.EditorFor(model => model.MondayClose, new { required="required" })
  <br>
  <p>Tuesday:</p>
  @Html.LabelFor(model => model.TuesdayOpen)
  @Html.EditorFor(model => model.TuesdayOpen, new { required="required" })
  @Html.LabelFor(model => model.TuesdayClose)
  @Html.EditorFor(model => model.TuesdayClose, new { required="required" })
  <br>
  <p>Wednesday:</p>
  @Html.LabelFor(model => model.WednesdayOpen)
  @Html.EditorFor(model => model.WednesdayOpen, new { required="required" })
  @Html.LabelFor(model => model.WednesdayClose)
  @Html.EditorFor(model => model.WednesdayClose, new {  required="required" })
  <br>
  <p>Thursday:</p>
  @Html.LabelFor(model => model.ThursdayOpen)
  @Html.EditorFor(model => model.ThursdayOpen, new { required="required" })
  @Html.LabelFor(model => model.ThursdayClose)
  @Html.EditorFor(model => model.ThursdayClose, new { required="required" })
  <br>
  <p>Friday:</p>
  @Html.LabelFor(model => model.FridayOpen)
  @Html.EditorFor(model => model.FridayOpen, new { required="required" })
  @Html.LabelFor(model => model.FridayClose)
  @Html.EditorFor(model => model.FridayClose, new { required="required" })
  <br>
  <p>Saturday:</p>
  @Html.LabelFor(model => model.SaturdayOpen)
  @Html.EditorFor(model => model.SaturdayOpen, new { required="required" })
  @Html.LabelFor(model => model.SaturdayClose)
  @Html.EditorFor(model => model.SaturdayClose, new { required="required" })
  <br>
  <input type="submit" value="Save" />
}
<br>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models

<h1>Restaurants:</h1>

@if (@Model.Count == 0)
{
  <h3>No Restaurants are in this database</h3>
}

@foreach (Restaurant restaurant in Model)
{
  <li>@Html.ActionLink($"{restaurant.Name}", "Show", new { id = restaurant.RestaurantId })</li>
}
<br>
<p>@Html.ActionLink("Add new Restaurant", "Create")</p>
<br>
<p>@Html.ActionLink("See By Cuisines", "Index", "Cuisines")</p>

BestRestaurants/Views/Restaurants/Show.cshtml
@{
  Layout="_Layout";
}

@using BestRestaurants.Models
@model BestRestaurants.Models.Restaurant

<h2>Restaurant Details:</h2>
<br>
<h3>Name: @Html.DisplayFor(model => model.Name)</h3>
<h3>Type of cuisine: @Model.Cuisine.Type</h3>
<h3>Times:</h3>
<h4>Sunday:</h4>
<p>From @Html.DisplayFor(model => model.SundayOpen) to @Html.DisplayFor(model => model.SundayClose)</p>
<h4>Monday:</h4>
<p>From @Html.DisplayFor(model => model.MondayOpen) to @Html.DisplayFor(model => model.MondayClose)</p>
<h4>Tuesday:</h4>
<p>From @Html.DisplayFor(model => model.TuesdayOpen) to @Html.DisplayFor(model => model.TuesdayClose)</p>
<h4>Wednesday:</h4>
<p>From @Html.DisplayFor(model => model.WednesdayOpen) to @Html.DisplayFor(model => model.WednesdayClose)</p>
<h4>Thursday:</h4>
<p>From @Html.DisplayFor(model => model.ThursdayOpen) to @Html.DisplayFor(model => model.ThursdayClose)</p>
<h4>Friday:</h4>
<p>From @Html.DisplayFor(model => model.FridayOpen) to @Html.DisplayFor(model => model.FridayClose)</p>
<h4>Saturday:</h4>
<p>From @Html.DisplayFor(model => model.SaturdayOpen) to @Html.DisplayFor(model => model.SaturdayClose)</p>
<br>
<p>@Html.ActionLink("Edit Details", "Edit", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Delete Entry", "Delete", new { id = Model.RestaurantId})</p>
<br>
<p>@Html.ActionLink("Show All Restaurants", "Index")</p>

BestRestaurants/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <title>Restaurants</title>
  </head>
  <body>
    @RenderBody()
  </body>
</html>